// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vcpu__Syms.h"


//======================

void Vcpu::trace(VerilatedVcdC* tfp, int, int) {
    tfp->spTrace()->addInitCb(&traceInit, __VlSymsp);
    traceRegister(tfp->spTrace());
}

void Vcpu::traceInit(void* userp, VerilatedVcd* tracep, uint32_t code) {
    // Callback from tracep->open()
    Vcpu__Syms* __restrict vlSymsp = static_cast<Vcpu__Syms*>(userp);
    if (!Verilated::calcUnusedSigs()) {
        VL_FATAL_MT(__FILE__, __LINE__, __FILE__,
                        "Turning on wave traces requires Verilated::traceEverOn(true) call before time 0.");
    }
    vlSymsp->__Vm_baseCode = code;
    tracep->module(vlSymsp->name());
    tracep->scopeEscape(' ');
    Vcpu::traceInitTop(vlSymsp, tracep);
    tracep->scopeEscape('.');
}

//======================


void Vcpu::traceInitTop(void* userp, VerilatedVcd* tracep) {
    Vcpu__Syms* __restrict vlSymsp = static_cast<Vcpu__Syms*>(userp);
    Vcpu* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    // Body
    {
        vlTOPp->traceInitSub0(userp, tracep);
    }
}

void Vcpu::traceInitSub0(void* userp, VerilatedVcd* tracep) {
    Vcpu__Syms* __restrict vlSymsp = static_cast<Vcpu__Syms*>(userp);
    Vcpu* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    const int c = vlSymsp->__Vm_baseCode;
    if (false && tracep && c) {}  // Prevent unused
    // Body
    {
        tracep->declBit(c+364,"clk", false,-1);
        tracep->declBit(c+365,"reset", false,-1);
        tracep->declBit(c+366,"joypad_start", false,-1);
        tracep->declBit(c+367,"joypad_select", false,-1);
        tracep->declBit(c+368,"joypad_A", false,-1);
        tracep->declBit(c+369,"joypad_B", false,-1);
        tracep->declBit(c+370,"joypad_down", false,-1);
        tracep->declBit(c+371,"joypad_up", false,-1);
        tracep->declBit(c+372,"joypad_left", false,-1);
        tracep->declBit(c+373,"joypad_right", false,-1);
        tracep->declBit(c+374,"ROM_ena", false,-1);
        tracep->declBus(c+375,"ROM_ad", false,-1, 20,0);
        tracep->declBit(c+376,"ROM_r_ena", false,-1);
        tracep->declBit(c+377,"ROM_w_ena", false,-1);
        tracep->declBus(c+378,"ROM_w_data", false,-1, 7,0);
        tracep->declBus(c+379,"ROM_r_data", false,-1, 7,0);
        tracep->declBit(c+380,"VRAM_ena", false,-1);
        tracep->declBus(c+381,"VRAM_ad", false,-1, 15,0);
        tracep->declBit(c+382,"VRAM_r_ena", false,-1);
        tracep->declBit(c+383,"VRAM_w_ena", false,-1);
        tracep->declBus(c+384,"VRAM_w_data", false,-1, 7,0);
        tracep->declBus(c+385,"VRAM_r_data", false,-1, 7,0);
        tracep->declBit(c+386,"WRAM_ena", false,-1);
        tracep->declBus(c+387,"WRAM_ad", false,-1, 15,0);
        tracep->declBit(c+388,"WRAM_r_ena", false,-1);
        tracep->declBit(c+389,"WRAM_w_ena", false,-1);
        tracep->declBus(c+390,"WRAM_w_data", false,-1, 7,0);
        tracep->declBus(c+391,"WRAM_r_data", false,-1, 7,0);
        tracep->declBit(c+392,"ERAM_ena", false,-1);
        tracep->declBus(c+393,"ERAM_ad", false,-1, 14,0);
        tracep->declBit(c+394,"ERAM_r_ena", false,-1);
        tracep->declBit(c+395,"ERAM_w_ena", false,-1);
        tracep->declBus(c+396,"ERAM_w_data", false,-1, 7,0);
        tracep->declBus(c+397,"ERAM_r_data", false,-1, 7,0);
        tracep->declBit(c+398,"OAM_ena", false,-1);
        tracep->declBus(c+399,"OAM_ad", false,-1, 15,0);
        tracep->declBit(c+400,"OAM_r_ena", false,-1);
        tracep->declBit(c+401,"OAM_w_ena", false,-1);
        tracep->declBus(c+402,"OAM_w_data", false,-1, 7,0);
        tracep->declBus(c+403,"OAM_r_data", false,-1, 7,0);
        tracep->declBit(c+404,"HRAM_ena", false,-1);
        tracep->declBus(c+405,"HRAM_ad", false,-1, 15,0);
        tracep->declBit(c+406,"HRAM_r_ena", false,-1);
        tracep->declBit(c+407,"HRAM_w_ena", false,-1);
        tracep->declBus(c+408,"HRAM_w_data", false,-1, 7,0);
        tracep->declBus(c+409,"HRAM_r_data", false,-1, 7,0);
        tracep->declBus(c+410,"pixel_data", false,-1, 1,0);
        tracep->declBit(c+411,"pixel_valid", false,-1);
        tracep->declBit(c+412,"hsync", false,-1);
        tracep->declBit(c+413,"vsync", false,-1);
        tracep->declBus(c+414,"MBC_version", false,-1, 3,0);
        tracep->declBus(c+415,"ROM_size", false,-1, 7,0);
        tracep->declBus(c+416,"RAM_size", false,-1, 7,0);
        tracep->declBit(c+364,"top clk", false,-1);
        tracep->declBit(c+365,"top reset", false,-1);
        tracep->declBit(c+366,"top joypad_start", false,-1);
        tracep->declBit(c+367,"top joypad_select", false,-1);
        tracep->declBit(c+368,"top joypad_A", false,-1);
        tracep->declBit(c+369,"top joypad_B", false,-1);
        tracep->declBit(c+370,"top joypad_down", false,-1);
        tracep->declBit(c+371,"top joypad_up", false,-1);
        tracep->declBit(c+372,"top joypad_left", false,-1);
        tracep->declBit(c+373,"top joypad_right", false,-1);
        tracep->declBit(c+374,"top ROM_ena", false,-1);
        tracep->declBus(c+375,"top ROM_ad", false,-1, 20,0);
        tracep->declBit(c+376,"top ROM_r_ena", false,-1);
        tracep->declBit(c+377,"top ROM_w_ena", false,-1);
        tracep->declBus(c+378,"top ROM_w_data", false,-1, 7,0);
        tracep->declBus(c+379,"top ROM_r_data", false,-1, 7,0);
        tracep->declBit(c+380,"top VRAM_ena", false,-1);
        tracep->declBus(c+381,"top VRAM_ad", false,-1, 15,0);
        tracep->declBit(c+382,"top VRAM_r_ena", false,-1);
        tracep->declBit(c+383,"top VRAM_w_ena", false,-1);
        tracep->declBus(c+384,"top VRAM_w_data", false,-1, 7,0);
        tracep->declBus(c+385,"top VRAM_r_data", false,-1, 7,0);
        tracep->declBit(c+386,"top WRAM_ena", false,-1);
        tracep->declBus(c+387,"top WRAM_ad", false,-1, 15,0);
        tracep->declBit(c+388,"top WRAM_r_ena", false,-1);
        tracep->declBit(c+389,"top WRAM_w_ena", false,-1);
        tracep->declBus(c+390,"top WRAM_w_data", false,-1, 7,0);
        tracep->declBus(c+391,"top WRAM_r_data", false,-1, 7,0);
        tracep->declBit(c+392,"top ERAM_ena", false,-1);
        tracep->declBus(c+393,"top ERAM_ad", false,-1, 14,0);
        tracep->declBit(c+394,"top ERAM_r_ena", false,-1);
        tracep->declBit(c+395,"top ERAM_w_ena", false,-1);
        tracep->declBus(c+396,"top ERAM_w_data", false,-1, 7,0);
        tracep->declBus(c+397,"top ERAM_r_data", false,-1, 7,0);
        tracep->declBit(c+398,"top OAM_ena", false,-1);
        tracep->declBus(c+399,"top OAM_ad", false,-1, 15,0);
        tracep->declBit(c+400,"top OAM_r_ena", false,-1);
        tracep->declBit(c+401,"top OAM_w_ena", false,-1);
        tracep->declBus(c+402,"top OAM_w_data", false,-1, 7,0);
        tracep->declBus(c+403,"top OAM_r_data", false,-1, 7,0);
        tracep->declBit(c+404,"top HRAM_ena", false,-1);
        tracep->declBus(c+405,"top HRAM_ad", false,-1, 15,0);
        tracep->declBit(c+406,"top HRAM_r_ena", false,-1);
        tracep->declBit(c+407,"top HRAM_w_ena", false,-1);
        tracep->declBus(c+408,"top HRAM_w_data", false,-1, 7,0);
        tracep->declBus(c+409,"top HRAM_r_data", false,-1, 7,0);
        tracep->declBus(c+410,"top pixel_data", false,-1, 1,0);
        tracep->declBit(c+411,"top pixel_valid", false,-1);
        tracep->declBit(c+412,"top hsync", false,-1);
        tracep->declBit(c+413,"top vsync", false,-1);
        tracep->declBus(c+414,"top MBC_version", false,-1, 3,0);
        tracep->declBus(c+415,"top ROM_size", false,-1, 7,0);
        tracep->declBus(c+416,"top RAM_size", false,-1, 7,0);
        tracep->declBus(c+1,"top IF", false,-1, 7,0);
        tracep->declBus(c+2,"top IE", false,-1, 7,0);
        tracep->declBus(c+3,"top LCDC", false,-1, 7,0);
        tracep->declBus(c+4,"top STAT", false,-1, 7,0);
        tracep->declBus(c+5,"top SCY", false,-1, 7,0);
        tracep->declBus(c+6,"top SCX", false,-1, 7,0);
        tracep->declBus(c+7,"top WX", false,-1, 7,0);
        tracep->declBus(c+8,"top WY", false,-1, 7,0);
        tracep->declBus(c+9,"top BGP", false,-1, 7,0);
        tracep->declBus(c+10,"top OBP0", false,-1, 7,0);
        tracep->declBus(c+11,"top OBP1", false,-1, 7,0);
        tracep->declBus(c+12,"top DMA", false,-1, 7,0);
        tracep->declBus(c+13,"top LY", false,-1, 7,0);
        tracep->declBus(c+14,"top LYC", false,-1, 7,0);
        tracep->declBit(c+15,"top cpu_mem_ena", false,-1);
        tracep->declBus(c+16,"top cpu_mem_ad", false,-1, 15,0);
        tracep->declBit(c+17,"top cpu_mem_r_ena", false,-1);
        tracep->declBit(c+18,"top cpu_mem_w_ena", false,-1);
        tracep->declBus(c+19,"top cpu_mem_w_data", false,-1, 7,0);
        tracep->declBus(c+300,"top cpu_mem_r_data", false,-1, 7,0);
        tracep->declBit(c+20,"top ppu_mem_ena", false,-1);
        tracep->declBus(c+21,"top ppu_mem_ad", false,-1, 15,0);
        tracep->declBit(c+22,"top ppu_mem_r_ena", false,-1);
        tracep->declBit(c+23,"top ppu_mem_w_ena", false,-1);
        tracep->declBus(c+24,"top ppu_mem_w_data", false,-1, 7,0);
        tracep->declBus(c+301,"top ppu_mem_r_data", false,-1, 7,0);
        tracep->declBit(c+25,"top dma_mem_ena", false,-1);
        tracep->declBus(c+26,"top dma_mem_ad", false,-1, 15,0);
        tracep->declBit(c+27,"top dma_mem_r_ena", false,-1);
        tracep->declBit(c+28,"top dma_mem_w_ena", false,-1);
        tracep->declBus(c+29,"top dma_mem_w_data", false,-1, 7,0);
        tracep->declBus(c+302,"top dma_mem_r_data", false,-1, 7,0);
        tracep->declBit(c+303,"top io_reg_ena", false,-1);
        tracep->declBus(c+304,"top io_reg_ad", false,-1, 15,0);
        tracep->declBit(c+305,"top io_reg_r_ena", false,-1);
        tracep->declBit(c+306,"top io_reg_w_ena", false,-1);
        tracep->declBus(c+307,"top io_reg_w_data", false,-1, 7,0);
        tracep->declBus(c+30,"top io_reg_r_data", false,-1, 7,0);
        tracep->declBit(c+31,"top DMA_start", false,-1);
        tracep->declBus(c+32,"top irq_clear", false,-1, 7,0);
        tracep->declBit(c+417,"top irq_joypad", false,-1);
        tracep->declBit(c+33,"top irq_LCD", false,-1);
        tracep->declBit(c+34,"top irq_vblank", false,-1);
        tracep->declBit(c+418,"top irq_serial", false,-1);
        tracep->declBit(c+418,"top cpu_stop", false,-1);
        tracep->declBit(c+35,"top PPU_STAT_w_ena", false,-1);
        tracep->declBus(c+36,"top PPU_STAT_w_data", false,-1, 7,0);
        tracep->declBit(c+37,"top PPU_LY_w_ena", false,-1);
        tracep->declBus(c+38,"top PPU_LY_w_data", false,-1, 7,0);
        tracep->declBit(c+364,"top u_CPU my_clk", false,-1);
        tracep->declBit(c+365,"top u_CPU reset", false,-1);
        tracep->declBit(c+15,"top u_CPU mem_ena", false,-1);
        tracep->declBus(c+16,"top u_CPU mem_ad", false,-1, 15,0);
        tracep->declBus(c+19,"top u_CPU mem_w_data", false,-1, 7,0);
        tracep->declBit(c+18,"top u_CPU mem_w_ena", false,-1);
        tracep->declBit(c+17,"top u_CPU mem_r_ena", false,-1);
        tracep->declBus(c+300,"top u_CPU mem_r_data", false,-1, 7,0);
        tracep->declBus(c+419,"top u_CPU mem_r_data_valid", false,-1, 7,0);
        tracep->declBus(c+2,"top u_CPU IE", false,-1, 7,0);
        tracep->declBus(c+1,"top u_CPU IF", false,-1, 7,0);
        tracep->declBus(c+32,"top u_CPU irq_clear", false,-1, 7,0);
        tracep->declBit(c+39,"top u_CPU halt", false,-1);
        tracep->declBus(c+40,"top u_CPU A_debug", false,-1, 7,0);
        tracep->declBus(c+41,"top u_CPU F_debug", false,-1, 7,0);
        tracep->declBus(c+42,"top u_CPU B_debug", false,-1, 7,0);
        tracep->declBus(c+43,"top u_CPU C_debug", false,-1, 7,0);
        tracep->declBus(c+44,"top u_CPU D_debug", false,-1, 7,0);
        tracep->declBus(c+45,"top u_CPU E_debug", false,-1, 7,0);
        tracep->declBus(c+46,"top u_CPU H_debug", false,-1, 7,0);
        tracep->declBus(c+47,"top u_CPU L_debug", false,-1, 7,0);
        tracep->declBus(c+48,"top u_CPU PC_debug", false,-1, 15,0);
        tracep->declBus(c+49,"top u_CPU SP_debug", false,-1, 15,0);
        tracep->declBus(c+50,"top u_CPU main_state_debug", false,-1, 7,0);
        tracep->declBit(c+51,"top u_CPU IME", false,-1);
        tracep->declBit(c+52,"top u_CPU IME_on", false,-1);
        tracep->declBit(c+53,"top u_CPU IME_off", false,-1);
        tracep->declBit(c+54,"top u_CPU EI_pending", false,-1);
        tracep->declBit(c+55,"top u_CPU EI_pending_on", false,-1);
        tracep->declBus(c+40,"top u_CPU A", false,-1, 7,0);
        tracep->declBus(c+41,"top u_CPU F", false,-1, 7,0);
        tracep->declBus(c+42,"top u_CPU B", false,-1, 7,0);
        tracep->declBus(c+43,"top u_CPU C", false,-1, 7,0);
        tracep->declBus(c+44,"top u_CPU D", false,-1, 7,0);
        tracep->declBus(c+45,"top u_CPU E", false,-1, 7,0);
        tracep->declBus(c+46,"top u_CPU H", false,-1, 7,0);
        tracep->declBus(c+47,"top u_CPU L", false,-1, 7,0);
        tracep->declBus(c+49,"top u_CPU SP", false,-1, 15,0);
        tracep->declBus(c+48,"top u_CPU PC", false,-1, 15,0);
        tracep->declBus(c+56,"top u_CPU IF_reg", false,-1, 7,0);
        tracep->declBus(c+308,"top u_CPU Operand_r8", false,-1, 7,0);
        tracep->declBus(c+57,"top u_CPU Operand_r8_ad", false,-1, 7,0);
        tracep->declBus(c+58,"top u_CPU Dest_r8", false,-1, 7,0);
        tracep->declBus(c+309,"top u_CPU Source_r8", false,-1, 7,0);
        tracep->declBit(c+59,"top u_CPU Condition", false,-1);
        tracep->declBus(c+310,"top u_CPU Operand_r16", false,-1, 15,0);
        tracep->declBus(c+60,"top u_CPU Operand_r16_ad", false,-1, 7,0);
        tracep->declBus(c+61,"top u_CPU Dest_r16mem", false,-1, 15,0);
        tracep->declBus(c+62,"top u_CPU Source_r16mem", false,-1, 15,0);
        tracep->declBus(c+311,"top u_CPU register_r16stk", false,-1, 15,0);
        tracep->declBus(c+63,"top u_CPU register_r16stk_ad", false,-1, 7,0);
        tracep->declBus(c+64,"top u_CPU T_clk_counter", false,-1, 7,0);
        tracep->declBus(c+65,"top u_CPU T_clk_counter_next", false,-1, 7,0);
        tracep->declBus(c+66,"top u_CPU opcode", false,-1, 7,0);
        tracep->declBit(c+67,"top u_CPU opcode_valid", false,-1);
        tracep->declBit(c+68,"top u_CPU prefix_valid", false,-1);
        tracep->declBus(c+69,"top u_CPU my_clk_counter", false,-1, 3,0);
        tracep->declBit(c+70,"top u_CPU T_cycle_ena", false,-1);
        tracep->declBit(c+420,"top u_CPU M_cycle_ena", false,-1);
        tracep->declBus(c+71,"top u_CPU mem_state", false,-1, 3,0);
        tracep->declBus(c+50,"top u_CPU main_state", false,-1, 7,0);
        tracep->declBus(c+72,"top u_CPU next_main_state", false,-1, 7,0);
        tracep->declBit(c+73,"top u_CPU reg_w_ena", false,-1);
        tracep->declBus(c+74,"top u_CPU reg_ad", false,-1, 7,0);
        tracep->declBus(c+312,"top u_CPU reg_w_data", false,-1, 15,0);
        tracep->declBus(c+75,"top u_CPU reg_ad_2", false,-1, 7,0);
        tracep->declBus(c+313,"top u_CPU reg_w_data_2", false,-1, 15,0);
        tracep->declBit(c+76,"top u_CPU PC_plus_ena", false,-1);
        tracep->declBus(c+77,"top u_CPU mem_ad_reg", false,-1, 15,0);
        tracep->declBus(c+78,"top u_CPU mem_w_data_reg", false,-1, 7,0);
        tracep->declBit(c+79,"top u_CPU mem_w_ena_reg", false,-1);
        tracep->declBit(c+80,"top u_CPU mem_r_ena_reg", false,-1);
        tracep->declBus(c+81,"top u_CPU mem_out_reg", false,-1, 7,0);
        tracep->declBit(c+82,"top u_CPU mem_control_r_ena", false,-1);
        tracep->declBit(c+83,"top u_CPU mem_control_w_ena", false,-1);
        tracep->declBus(c+84,"top u_CPU mem_control_ad", false,-1, 15,0);
        tracep->declBus(c+314,"top u_CPU mem_control_w_data", false,-1, 7,0);
        tracep->declBus(c+81,"top u_CPU mem_control_r_data", false,-1, 7,0);
        tracep->declBus(c+85,"top u_CPU tem_reg", false,-1, 7,0);
        tracep->declBit(c+86,"top u_CPU tem_reg_w_ena", false,-1);
        tracep->declBus(c+315,"top u_CPU tem_reg_w_data", false,-1, 7,0);
        tracep->declBus(c+87,"top u_CPU imm8_reg", false,-1, 7,0);
        tracep->declBit(c+88,"top u_CPU imm8_reg_clear", false,-1);
        tracep->declBus(c+89,"top u_CPU imm16_reg", false,-1, 15,0);
        tracep->declBit(c+90,"top u_CPU imm16_reg_clear", false,-1);
        tracep->declBus(c+421,"top u_CPU fetch_T1", false,-1, 31,0);
        tracep->declBus(c+422,"top u_CPU fetch_T2", false,-1, 31,0);
        tracep->declBus(c+423,"top u_CPU fetch_T3", false,-1, 31,0);
        tracep->declBus(c+424,"top u_CPU fetch_T4", false,-1, 31,0);
        tracep->declBus(c+425,"top u_CPU imm8_T1", false,-1, 31,0);
        tracep->declBus(c+426,"top u_CPU imm8_T2", false,-1, 31,0);
        tracep->declBus(c+427,"top u_CPU imm8_T3", false,-1, 31,0);
        tracep->declBus(c+428,"top u_CPU imm8_T4", false,-1, 31,0);
        tracep->declBus(c+429,"top u_CPU imm16_T1", false,-1, 31,0);
        tracep->declBus(c+430,"top u_CPU imm16_T2", false,-1, 31,0);
        tracep->declBus(c+431,"top u_CPU imm16_T3", false,-1, 31,0);
        tracep->declBus(c+432,"top u_CPU imm16_T4", false,-1, 31,0);
        tracep->declBus(c+433,"top u_CPU prefix_T1", false,-1, 31,0);
        tracep->declBus(c+434,"top u_CPU prefix_T2", false,-1, 31,0);
        tracep->declBus(c+435,"top u_CPU prefix_T3", false,-1, 31,0);
        tracep->declBus(c+436,"top u_CPU prefix_T4", false,-1, 31,0);
        tracep->declBus(c+437,"top u_CPU EXECUTE", false,-1, 31,0);
        tracep->declBus(c+438,"top u_CPU INTERRUPT", false,-1, 31,0);
        tracep->declBus(c+439,"top u_CPU HALT", false,-1, 31,0);
        tracep->declBus(c+440,"top u_CPU EXECUTE_prefix", false,-1, 31,0);
        tracep->declBus(c+441,"top u_CPU imm16_T5", false,-1, 31,0);
        tracep->declBus(c+442,"top u_CPU imm16_T6", false,-1, 31,0);
        tracep->declBus(c+443,"top u_CPU imm16_T7", false,-1, 31,0);
        tracep->declBus(c+444,"top u_CPU imm16_T8", false,-1, 31,0);
        tracep->declBus(c+445,"top u_CPU STOP", false,-1, 31,0);
        tracep->declBus(c+91,"top u_CPU a_8", false,-1, 7,0);
        tracep->declBus(c+316,"top u_CPU b_8", false,-1, 7,0);
        tracep->declBus(c+92,"top u_CPU alu_op_8", false,-1, 4,0);
        tracep->declBit(c+93,"top u_CPU cin_8", false,-1);
        tracep->declBus(c+317,"top u_CPU flag_8", false,-1, 3,0);
        tracep->declBus(c+318,"top u_CPU alu_result_8", false,-1, 7,0);
        tracep->declBus(c+91,"top u_CPU ins00 a", false,-1, 7,0);
        tracep->declBus(c+316,"top u_CPU ins00 b", false,-1, 7,0);
        tracep->declBus(c+92,"top u_CPU ins00 alu_op", false,-1, 4,0);
        tracep->declBit(c+93,"top u_CPU ins00 cin", false,-1);
        tracep->declBus(c+317,"top u_CPU ins00 flag", false,-1, 3,0);
        tracep->declBus(c+318,"top u_CPU ins00 result", false,-1, 7,0);
        tracep->declBus(c+319,"top u_CPU ins00 tem9", false,-1, 8,0);
        tracep->declBus(c+320,"top u_CPU ins00 tem5", false,-1, 4,0);
        tracep->declBit(c+364,"top u_io_register clk", false,-1);
        tracep->declBit(c+365,"top u_io_register reset", false,-1);
        tracep->declBit(c+303,"top u_io_register io_reg_ena", false,-1);
        tracep->declBus(c+304,"top u_io_register io_reg_ad", false,-1, 15,0);
        tracep->declBit(c+305,"top u_io_register io_reg_r_ena", false,-1);
        tracep->declBit(c+306,"top u_io_register io_reg_w_ena", false,-1);
        tracep->declBus(c+307,"top u_io_register io_reg_w_data", false,-1, 7,0);
        tracep->declBus(c+30,"top u_io_register io_reg_r_data", false,-1, 7,0);
        tracep->declBus(c+1,"top u_io_register IF_out", false,-1, 7,0);
        tracep->declBus(c+2,"top u_io_register IE_out", false,-1, 7,0);
        tracep->declBus(c+94,"top u_io_register TAC_out", false,-1, 7,0);
        tracep->declBus(c+95,"top u_io_register TMA_out", false,-1, 7,0);
        tracep->declBus(c+4,"top u_io_register STAT_out", false,-1, 7,0);
        tracep->declBus(c+13,"top u_io_register LY_out", false,-1, 7,0);
        tracep->declBus(c+3,"top u_io_register LCDC_out", false,-1, 7,0);
        tracep->declBus(c+5,"top u_io_register SCY_out", false,-1, 7,0);
        tracep->declBus(c+6,"top u_io_register SCX_out", false,-1, 7,0);
        tracep->declBus(c+14,"top u_io_register LYC_out", false,-1, 7,0);
        tracep->declBus(c+9,"top u_io_register BGP_out", false,-1, 7,0);
        tracep->declBus(c+10,"top u_io_register OBP0_out", false,-1, 7,0);
        tracep->declBus(c+11,"top u_io_register OBP1_out", false,-1, 7,0);
        tracep->declBus(c+7,"top u_io_register WX_out", false,-1, 7,0);
        tracep->declBus(c+8,"top u_io_register WY_out", false,-1, 7,0);
        tracep->declBus(c+12,"top u_io_register DMA_out", false,-1, 7,0);
        tracep->declBus(c+32,"top u_io_register irq_clear", false,-1, 7,0);
        tracep->declBit(c+31,"top u_io_register DMA_start_out", false,-1);
        tracep->declBit(c+34,"top u_io_register irq_vblank", false,-1);
        tracep->declBit(c+33,"top u_io_register irq_LCD", false,-1);
        tracep->declBit(c+418,"top u_io_register irq_serial", false,-1);
        tracep->declBit(c+418,"top u_io_register cpu_stop", false,-1);
        tracep->declBit(c+35,"top u_io_register PPU_STAT_w_ena", false,-1);
        tracep->declBus(c+36,"top u_io_register PPU_STAT_w_data", false,-1, 7,0);
        tracep->declBit(c+37,"top u_io_register PPU_LY_w_ena", false,-1);
        tracep->declBus(c+38,"top u_io_register PPU_LY_w_data", false,-1, 7,0);
        tracep->declBit(c+366,"top u_io_register joypad_start", false,-1);
        tracep->declBit(c+367,"top u_io_register joypad_select", false,-1);
        tracep->declBit(c+368,"top u_io_register joypad_A", false,-1);
        tracep->declBit(c+369,"top u_io_register joypad_B", false,-1);
        tracep->declBit(c+370,"top u_io_register joypad_down", false,-1);
        tracep->declBit(c+371,"top u_io_register joypad_up", false,-1);
        tracep->declBit(c+372,"top u_io_register joypad_left", false,-1);
        tracep->declBit(c+373,"top u_io_register joypad_right", false,-1);
        tracep->declBus(c+1,"top u_io_register IF", false,-1, 7,0);
        tracep->declBus(c+2,"top u_io_register IE", false,-1, 7,0);
        tracep->declBus(c+94,"top u_io_register TAC", false,-1, 7,0);
        tracep->declBus(c+95,"top u_io_register TMA", false,-1, 7,0);
        tracep->declBus(c+446,"top u_io_register DIV", false,-1, 7,0);
        tracep->declBus(c+447,"top u_io_register TIMA", false,-1, 7,0);
        tracep->declBus(c+4,"top u_io_register STAT", false,-1, 7,0);
        tracep->declBus(c+13,"top u_io_register LY", false,-1, 7,0);
        tracep->declBus(c+3,"top u_io_register LCDC", false,-1, 7,0);
        tracep->declBus(c+5,"top u_io_register SCY", false,-1, 7,0);
        tracep->declBus(c+6,"top u_io_register SCX", false,-1, 7,0);
        tracep->declBus(c+14,"top u_io_register LYC", false,-1, 7,0);
        tracep->declBus(c+9,"top u_io_register BGP", false,-1, 7,0);
        tracep->declBus(c+10,"top u_io_register OBP0", false,-1, 7,0);
        tracep->declBus(c+11,"top u_io_register OBP1", false,-1, 7,0);
        tracep->declBus(c+7,"top u_io_register WX", false,-1, 7,0);
        tracep->declBus(c+8,"top u_io_register WY", false,-1, 7,0);
        tracep->declBus(c+12,"top u_io_register DMA", false,-1, 7,0);
        tracep->declBit(c+31,"top u_io_register DMA_start", false,-1);
        tracep->declBit(c+96,"top u_io_register irq_timer_wire", false,-1);
        tracep->declBit(c+321,"top u_io_register IF_w_ena", false,-1);
        tracep->declBit(c+322,"top u_io_register IE_w_ena", false,-1);
        tracep->declBus(c+97,"top u_io_register div_r_data", false,-1, 7,0);
        tracep->declBit(c+323,"top u_io_register div_w_ena", false,-1);
        tracep->declBit(c+324,"top u_io_register div_r_ena", false,-1);
        tracep->declBus(c+98,"top u_io_register tima_r_data", false,-1, 7,0);
        tracep->declBit(c+325,"top u_io_register tima_w_ena", false,-1);
        tracep->declBit(c+326,"top u_io_register tima_r_ena", false,-1);
        tracep->declBus(c+99,"top u_io_register tma_r_data", false,-1, 7,0);
        tracep->declBit(c+327,"top u_io_register tma_r_ena", false,-1);
        tracep->declBit(c+328,"top u_io_register tma_w_ena", false,-1);
        tracep->declBus(c+100,"top u_io_register tac_r_data", false,-1, 7,0);
        tracep->declBit(c+329,"top u_io_register tac_r_ena", false,-1);
        tracep->declBit(c+330,"top u_io_register tac_w_ena", false,-1);
        tracep->declBus(c+101,"top u_io_register dma_r_data", false,-1, 7,0);
        tracep->declBit(c+331,"top u_io_register dma_r_ena", false,-1);
        tracep->declBit(c+332,"top u_io_register dma_w_ena", false,-1);
        tracep->declBus(c+102,"top u_io_register ppu_io_r_data", false,-1, 7,0);
        tracep->declBit(c+333,"top u_io_register ppu_io_r_ena", false,-1);
        tracep->declBit(c+334,"top u_io_register ppu_io_w_ena", false,-1);
        tracep->declBus(c+103,"top u_io_register stat_r_data", false,-1, 7,0);
        tracep->declBit(c+335,"top u_io_register stat_r_ena", false,-1);
        tracep->declBit(c+336,"top u_io_register stat_w_ena", false,-1);
        tracep->declBus(c+104,"top u_io_register ly_r_data", false,-1, 7,0);
        tracep->declBit(c+337,"top u_io_register ly_r_ena", false,-1);
        tracep->declBit(c+338,"top u_io_register ly_w_ena", false,-1);
        tracep->declBit(c+339,"top u_io_register joy_r_ena", false,-1);
        tracep->declBit(c+340,"top u_io_register joy_w_ena", false,-1);
        tracep->declBus(c+105,"top u_io_register r_state", false,-1, 3,0);
        tracep->declBus(c+341,"top u_io_register next", false,-1, 3,0);
        tracep->declBus(c+106,"top u_io_register JOY", false,-1, 7,0);
        tracep->declBit(c+107,"top u_io_register irq_joypad", false,-1);
        tracep->declBit(c+364,"top u_io_register inst_IF clk", false,-1);
        tracep->declBit(c+365,"top u_io_register inst_IF reset", false,-1);
        tracep->declBus(c+304,"top u_io_register inst_IF ad", false,-1, 15,0);
        tracep->declBus(c+307,"top u_io_register inst_IF w_data", false,-1, 7,0);
        tracep->declBit(c+321,"top u_io_register inst_IF w_ena", false,-1);
        tracep->declBus(c+1,"top u_io_register inst_IF IF", false,-1, 7,0);
        tracep->declBus(c+32,"top u_io_register inst_IF irq_clear", false,-1, 7,0);
        tracep->declBit(c+107,"top u_io_register inst_IF irq_joypad", false,-1);
        tracep->declBit(c+418,"top u_io_register inst_IF irq_serial", false,-1);
        tracep->declBit(c+96,"top u_io_register inst_IF irq_timer", false,-1);
        tracep->declBit(c+33,"top u_io_register inst_IF irq_LCD", false,-1);
        tracep->declBit(c+34,"top u_io_register inst_IF irq_vblank", false,-1);
        tracep->declBus(c+108,"top u_io_register inst_IF IF_reg", false,-1, 7,0);
        tracep->declBit(c+364,"top u_io_register inst_IE clk", false,-1);
        tracep->declBit(c+365,"top u_io_register inst_IE reset", false,-1);
        tracep->declBus(c+304,"top u_io_register inst_IE ad", false,-1, 15,0);
        tracep->declBus(c+307,"top u_io_register inst_IE w_data", false,-1, 7,0);
        tracep->declBit(c+322,"top u_io_register inst_IE w_ena", false,-1);
        tracep->declBus(c+2,"top u_io_register inst_IE IE", false,-1, 7,0);
        tracep->declBus(c+109,"top u_io_register inst_IE IE_reg", false,-1, 7,0);
        tracep->declBit(c+364,"top u_io_register inst_DIV clk", false,-1);
        tracep->declBit(c+365,"top u_io_register inst_DIV reset", false,-1);
        tracep->declBit(c+323,"top u_io_register inst_DIV w_ena", false,-1);
        tracep->declBit(c+324,"top u_io_register inst_DIV r_ena", false,-1);
        tracep->declBus(c+304,"top u_io_register inst_DIV ad", false,-1, 15,0);
        tracep->declBus(c+307,"top u_io_register inst_DIV w_data", false,-1, 7,0);
        tracep->declBus(c+97,"top u_io_register inst_DIV r_data", false,-1, 7,0);
        tracep->declBit(c+418,"top u_io_register inst_DIV cpu_stop", false,-1);
        tracep->declBus(c+110,"top u_io_register inst_DIV my_clk_counter", false,-1, 4,0);
        tracep->declBus(c+111,"top u_io_register inst_DIV T_clk_counter", false,-1, 15,0);
        tracep->declBit(c+364,"top u_io_register inst_TIMA clk", false,-1);
        tracep->declBit(c+365,"top u_io_register inst_TIMA reset", false,-1);
        tracep->declBus(c+304,"top u_io_register inst_TIMA ad", false,-1, 15,0);
        tracep->declBit(c+325,"top u_io_register inst_TIMA w_ena", false,-1);
        tracep->declBit(c+326,"top u_io_register inst_TIMA r_ena", false,-1);
        tracep->declBus(c+307,"top u_io_register inst_TIMA w_data", false,-1, 7,0);
        tracep->declBus(c+98,"top u_io_register inst_TIMA r_data", false,-1, 7,0);
        tracep->declBus(c+94,"top u_io_register inst_TIMA TAC", false,-1, 7,0);
        tracep->declBus(c+95,"top u_io_register inst_TIMA TMA", false,-1, 7,0);
        tracep->declBit(c+96,"top u_io_register inst_TIMA irq_timer", false,-1);
        tracep->declBus(c+112,"top u_io_register inst_TIMA TIMA", false,-1, 7,0);
        tracep->declBus(c+113,"top u_io_register inst_TIMA my_clk_counter", false,-1, 3,0);
        tracep->declBus(c+114,"top u_io_register inst_TIMA T_clk_counter", false,-1, 15,0);
        tracep->declBit(c+115,"top u_io_register inst_TIMA T_cycle_ena", false,-1);
        tracep->declBit(c+116,"top u_io_register inst_TIMA M_cycle_ena", false,-1);
        tracep->declBus(c+117,"top u_io_register inst_TIMA M_4_counter", false,-1, 15,0);
        tracep->declBus(c+118,"top u_io_register inst_TIMA M_16_counter", false,-1, 15,0);
        tracep->declBus(c+119,"top u_io_register inst_TIMA M_64_counter", false,-1, 15,0);
        tracep->declBus(c+120,"top u_io_register inst_TIMA M_256_counter", false,-1, 15,0);
        tracep->declBit(c+121,"top u_io_register inst_TIMA TIMA_M_4_ena", false,-1);
        tracep->declBit(c+122,"top u_io_register inst_TIMA TIMA_M_16_ena", false,-1);
        tracep->declBit(c+123,"top u_io_register inst_TIMA TIMA_M_64_ena", false,-1);
        tracep->declBit(c+124,"top u_io_register inst_TIMA TIMA_M_256_ena", false,-1);
        tracep->declBit(c+125,"top u_io_register inst_TIMA TIMA_ena", false,-1);
        tracep->declBit(c+126,"top u_io_register inst_TIMA TIMA_overflow", false,-1);
        tracep->declBit(c+364,"top u_io_register inst_TMA clk", false,-1);
        tracep->declBit(c+365,"top u_io_register inst_TMA reset", false,-1);
        tracep->declBus(c+304,"top u_io_register inst_TMA ad", false,-1, 15,0);
        tracep->declBit(c+328,"top u_io_register inst_TMA w_ena", false,-1);
        tracep->declBit(c+327,"top u_io_register inst_TMA r_ena", false,-1);
        tracep->declBus(c+307,"top u_io_register inst_TMA w_data", false,-1, 7,0);
        tracep->declBus(c+99,"top u_io_register inst_TMA r_data", false,-1, 7,0);
        tracep->declBus(c+95,"top u_io_register inst_TMA TMA", false,-1, 7,0);
        tracep->declBus(c+95,"top u_io_register inst_TMA TMA_reg", false,-1, 7,0);
        tracep->declBit(c+364,"top u_io_register inst_TAC clk", false,-1);
        tracep->declBit(c+365,"top u_io_register inst_TAC reset", false,-1);
        tracep->declBus(c+304,"top u_io_register inst_TAC ad", false,-1, 15,0);
        tracep->declBit(c+330,"top u_io_register inst_TAC w_ena", false,-1);
        tracep->declBit(c+329,"top u_io_register inst_TAC r_ena", false,-1);
        tracep->declBus(c+307,"top u_io_register inst_TAC w_data", false,-1, 7,0);
        tracep->declBus(c+100,"top u_io_register inst_TAC r_data", false,-1, 7,0);
        tracep->declBus(c+94,"top u_io_register inst_TAC TAC", false,-1, 7,0);
        tracep->declBus(c+127,"top u_io_register inst_TAC TAC_reg", false,-1, 7,0);
        tracep->declBit(c+364,"top u_io_register inst_DMA clk", false,-1);
        tracep->declBit(c+365,"top u_io_register inst_DMA reset", false,-1);
        tracep->declBus(c+304,"top u_io_register inst_DMA ad", false,-1, 15,0);
        tracep->declBit(c+332,"top u_io_register inst_DMA w_ena", false,-1);
        tracep->declBit(c+331,"top u_io_register inst_DMA r_ena", false,-1);
        tracep->declBus(c+307,"top u_io_register inst_DMA w_data", false,-1, 7,0);
        tracep->declBus(c+101,"top u_io_register inst_DMA r_data", false,-1, 7,0);
        tracep->declBus(c+12,"top u_io_register inst_DMA DMA", false,-1, 7,0);
        tracep->declBit(c+31,"top u_io_register inst_DMA DMA_start", false,-1);
        tracep->declBus(c+12,"top u_io_register inst_DMA DMA_reg", false,-1, 7,0);
        tracep->declBit(c+364,"top u_io_register inst_PPU_IO clk", false,-1);
        tracep->declBit(c+365,"top u_io_register inst_PPU_IO reset", false,-1);
        tracep->declBus(c+304,"top u_io_register inst_PPU_IO ad", false,-1, 15,0);
        tracep->declBit(c+334,"top u_io_register inst_PPU_IO w_ena", false,-1);
        tracep->declBit(c+333,"top u_io_register inst_PPU_IO r_ena", false,-1);
        tracep->declBus(c+307,"top u_io_register inst_PPU_IO w_data", false,-1, 7,0);
        tracep->declBus(c+102,"top u_io_register inst_PPU_IO r_data", false,-1, 7,0);
        tracep->declBus(c+3,"top u_io_register inst_PPU_IO LCDC", false,-1, 7,0);
        tracep->declBus(c+5,"top u_io_register inst_PPU_IO SCY", false,-1, 7,0);
        tracep->declBus(c+6,"top u_io_register inst_PPU_IO SCX", false,-1, 7,0);
        tracep->declBus(c+14,"top u_io_register inst_PPU_IO LYC", false,-1, 7,0);
        tracep->declBus(c+9,"top u_io_register inst_PPU_IO BGP", false,-1, 7,0);
        tracep->declBus(c+10,"top u_io_register inst_PPU_IO OBP0", false,-1, 7,0);
        tracep->declBus(c+11,"top u_io_register inst_PPU_IO OBP1", false,-1, 7,0);
        tracep->declBus(c+7,"top u_io_register inst_PPU_IO WX", false,-1, 7,0);
        tracep->declBus(c+8,"top u_io_register inst_PPU_IO WY", false,-1, 7,0);
        tracep->declBus(c+3,"top u_io_register inst_PPU_IO LCDC_reg", false,-1, 7,0);
        tracep->declBus(c+5,"top u_io_register inst_PPU_IO SCY_reg", false,-1, 7,0);
        tracep->declBus(c+6,"top u_io_register inst_PPU_IO SCX_reg", false,-1, 7,0);
        tracep->declBus(c+14,"top u_io_register inst_PPU_IO LYC_reg", false,-1, 7,0);
        tracep->declBus(c+9,"top u_io_register inst_PPU_IO BGP_reg", false,-1, 7,0);
        tracep->declBus(c+10,"top u_io_register inst_PPU_IO OBP0_reg", false,-1, 7,0);
        tracep->declBus(c+11,"top u_io_register inst_PPU_IO OBP1_reg", false,-1, 7,0);
        tracep->declBus(c+7,"top u_io_register inst_PPU_IO WX_reg", false,-1, 7,0);
        tracep->declBus(c+8,"top u_io_register inst_PPU_IO WY_reg", false,-1, 7,0);
        tracep->declBit(c+364,"top u_io_register inst_STAT clk", false,-1);
        tracep->declBit(c+365,"top u_io_register inst_STAT reset", false,-1);
        tracep->declBus(c+304,"top u_io_register inst_STAT ad", false,-1, 15,0);
        tracep->declBit(c+336,"top u_io_register inst_STAT w_ena", false,-1);
        tracep->declBit(c+335,"top u_io_register inst_STAT r_ena", false,-1);
        tracep->declBus(c+307,"top u_io_register inst_STAT w_data", false,-1, 7,0);
        tracep->declBus(c+103,"top u_io_register inst_STAT r_data", false,-1, 7,0);
        tracep->declBus(c+36,"top u_io_register inst_STAT PPU_STAT_w_data", false,-1, 7,0);
        tracep->declBit(c+35,"top u_io_register inst_STAT PPU_STAT_w_ena", false,-1);
        tracep->declBus(c+4,"top u_io_register inst_STAT STAT", false,-1, 7,0);
        tracep->declBus(c+4,"top u_io_register inst_STAT STAT_reg", false,-1, 7,0);
        tracep->declBit(c+364,"top u_io_register inst_LY clk", false,-1);
        tracep->declBit(c+365,"top u_io_register inst_LY reset", false,-1);
        tracep->declBus(c+304,"top u_io_register inst_LY ad", false,-1, 15,0);
        tracep->declBit(c+338,"top u_io_register inst_LY w_ena", false,-1);
        tracep->declBit(c+337,"top u_io_register inst_LY r_ena", false,-1);
        tracep->declBus(c+307,"top u_io_register inst_LY w_data", false,-1, 7,0);
        tracep->declBus(c+104,"top u_io_register inst_LY r_data", false,-1, 7,0);
        tracep->declBus(c+38,"top u_io_register inst_LY PPU_LY_w_data", false,-1, 7,0);
        tracep->declBit(c+37,"top u_io_register inst_LY PPU_LY_w_ena", false,-1);
        tracep->declBus(c+13,"top u_io_register inst_LY LY", false,-1, 7,0);
        tracep->declBus(c+13,"top u_io_register inst_LY LY_reg", false,-1, 7,0);
        tracep->declBit(c+364,"top u_PPU clk", false,-1);
        tracep->declBit(c+365,"top u_PPU reset", false,-1);
        tracep->declBit(c+20,"top u_PPU mem_ena", false,-1);
        tracep->declBit(c+22,"top u_PPU mem_r_ena", false,-1);
        tracep->declBit(c+23,"top u_PPU mem_w_ena", false,-1);
        tracep->declBus(c+21,"top u_PPU mem_ad", false,-1, 15,0);
        tracep->declBus(c+24,"top u_PPU mem_w_data", false,-1, 7,0);
        tracep->declBus(c+301,"top u_PPU mem_r_data", false,-1, 7,0);
        tracep->declBus(c+3,"top u_PPU LCDC", false,-1, 7,0);
        tracep->declBus(c+4,"top u_PPU STAT", false,-1, 7,0);
        tracep->declBus(c+5,"top u_PPU SCY", false,-1, 7,0);
        tracep->declBus(c+6,"top u_PPU SCX", false,-1, 7,0);
        tracep->declBus(c+13,"top u_PPU LY", false,-1, 7,0);
        tracep->declBus(c+14,"top u_PPU LYC", false,-1, 7,0);
        tracep->declBus(c+9,"top u_PPU BGP", false,-1, 7,0);
        tracep->declBus(c+10,"top u_PPU OBP0", false,-1, 7,0);
        tracep->declBus(c+11,"top u_PPU OBP1", false,-1, 7,0);
        tracep->declBus(c+7,"top u_PPU WX", false,-1, 7,0);
        tracep->declBus(c+8,"top u_PPU WY", false,-1, 7,0);
        tracep->declBus(c+410,"top u_PPU pixel_data", false,-1, 1,0);
        tracep->declBit(c+411,"top u_PPU pixel_valid", false,-1);
        tracep->declBit(c+412,"top u_PPU hsync", false,-1);
        tracep->declBit(c+413,"top u_PPU vsync", false,-1);
        tracep->declBit(c+34,"top u_PPU irq_vblank", false,-1);
        tracep->declBit(c+33,"top u_PPU irq_LCD", false,-1);
        tracep->declBus(c+36,"top u_PPU PPU_STAT_w_data", false,-1, 7,0);
        tracep->declBit(c+35,"top u_PPU PPU_STAT_w_ena", false,-1);
        tracep->declBus(c+38,"top u_PPU PPU_LY_w_data", false,-1, 7,0);
        tracep->declBit(c+37,"top u_PPU PPU_LY_w_ena", false,-1);
        tracep->declBus(c+128,"top u_PPU clk_counter", false,-1, 3,0);
        tracep->declBit(c+129,"top u_PPU T_cycle_ena", false,-1);
        tracep->declBus(c+130,"top u_PPU m_clk_counter", false,-1, 31,0);
        tracep->declBus(c+131,"top u_PPU main_state", false,-1, 4,0);
        tracep->declBus(c+421,"top u_PPU IDLE", false,-1, 31,0);
        tracep->declBus(c+422,"top u_PPU OAM_SCAN", false,-1, 31,0);
        tracep->declBus(c+423,"top u_PPU DRAW_PIXEL", false,-1, 31,0);
        tracep->declBus(c+424,"top u_PPU VBLANK", false,-1, 31,0);
        tracep->declBus(c+132,"top u_PPU line_counter", false,-1, 7,0);
        tracep->declBit(c+133,"top u_PPU mode0_enter", false,-1);
        tracep->declBit(c+134,"top u_PPU mode1_enter", false,-1);
        tracep->declBit(c+135,"top u_PPU mode2_enter", false,-1);
        tracep->declBit(c+136,"top u_PPU mode3_enter", false,-1);
        tracep->declQuad(c+137,"top u_PPU oam_scan", false,-1, 39,0);
        tracep->declArray(c+139,"top u_PPU obj_ad", false,-1, 159,0);
        tracep->declArray(c+144,"top u_PPU obj_y", false,-1, 79,0);
        tracep->declArray(c+147,"top u_PPU obj_x", false,-1, 79,0);
        tracep->declArray(c+150,"top u_PPU obj_tile_index", false,-1, 79,0);
        tracep->declArray(c+153,"top u_PPU obj_flag", false,-1, 79,0);
        tracep->declBus(c+156,"top u_PPU array_index", false,-1, 3,0);
        tracep->declBus(c+157,"top u_PPU valid_obj_counter", false,-1, 3,0);
        tracep->declArray(c+158,"top u_PPU obj_scanline", false,-1, 511,0);
        tracep->declArray(c+174,"top u_PPU obj_priority", false,-1, 255,0);
        tracep->declArray(c+182,"top u_PPU obj_palette", false,-1, 255,0);
        tracep->declArray(c+190,"top u_PPU obj_x_buffer", false,-1, 2047,0);
        tracep->declBus(c+254,"top u_PPU sub_state", false,-1, 15,0);
        tracep->declBus(c+422,"top u_PPU OAM_40_SCAN", false,-1, 31,0);
        tracep->declBus(c+423,"top u_PPU OAM_X_SCAN", false,-1, 31,0);
        tracep->declBus(c+424,"top u_PPU OAM_INDEX_SCAN", false,-1, 31,0);
        tracep->declBus(c+425,"top u_PPU OAM_FLAG_SCAN", false,-1, 31,0);
        tracep->declBus(c+426,"top u_PPU OAM_OBJ_SCANLINE", false,-1, 31,0);
        tracep->declBus(c+427,"top u_PPU TILE_FETCH", false,-1, 31,0);
        tracep->declBus(c+255,"top u_PPU sub_counter_1", false,-1, 15,0);
        tracep->declBus(c+256,"top u_PPU sub_counter_2", false,-1, 15,0);
        tracep->declBus(c+257,"top u_PPU sub_counter_3", false,-1, 15,0);
        tracep->declBus(c+258,"top u_PPU mode3_state", false,-1, 3,0);
        tracep->declBus(c+259,"top u_PPU mode3_counter_1", false,-1, 7,0);
        tracep->declBus(c+260,"top u_PPU map_x", false,-1, 7,0);
        tracep->declBus(c+261,"top u_PPU map_y", false,-1, 7,0);
        tracep->declBus(c+262,"top u_PPU win_x", false,-1, 7,0);
        tracep->declBus(c+263,"top u_PPU win_y", false,-1, 7,0);
        tracep->declArray(c+264,"top u_PPU tile_buffer", false,-1, 511,0);
        tracep->declBus(c+280,"top u_PPU tile_buffer_index", false,-1, 7,0);
        tracep->declBus(c+281,"top u_PPU i", false,-1, 31,0);
        tracep->declBus(c+282,"top u_PPU obj_row", false,-1, 7,0);
        tracep->declBit(c+283,"top u_PPU is_win_active", false,-1);
        tracep->declBus(c+284,"top u_PPU pixel_offset", false,-1, 2,0);
        tracep->declBus(c+342,"top u_PPU shifted_data", false,-1, 7,0);
        tracep->declBit(c+364,"top u_Memory_Interface clk", false,-1);
        tracep->declBit(c+365,"top u_Memory_Interface reset", false,-1);
        tracep->declBit(c+15,"top u_Memory_Interface cpu_mem_ena", false,-1);
        tracep->declBus(c+16,"top u_Memory_Interface cpu_mem_ad", false,-1, 15,0);
        tracep->declBit(c+18,"top u_Memory_Interface cpu_mem_w_ena", false,-1);
        tracep->declBit(c+17,"top u_Memory_Interface cpu_mem_r_ena", false,-1);
        tracep->declBus(c+19,"top u_Memory_Interface cpu_w_data", false,-1, 7,0);
        tracep->declBus(c+300,"top u_Memory_Interface cpu_r_data", false,-1, 7,0);
        tracep->declBit(c+20,"top u_Memory_Interface ppu_mem_ena", false,-1);
        tracep->declBus(c+21,"top u_Memory_Interface ppu_mem_ad", false,-1, 15,0);
        tracep->declBit(c+23,"top u_Memory_Interface ppu_mem_w_ena", false,-1);
        tracep->declBit(c+22,"top u_Memory_Interface ppu_mem_r_ena", false,-1);
        tracep->declBus(c+24,"top u_Memory_Interface ppu_w_data", false,-1, 7,0);
        tracep->declBus(c+301,"top u_Memory_Interface ppu_r_data", false,-1, 7,0);
        tracep->declBit(c+25,"top u_Memory_Interface dma_mem_ena", false,-1);
        tracep->declBus(c+26,"top u_Memory_Interface dma_mem_ad", false,-1, 15,0);
        tracep->declBit(c+28,"top u_Memory_Interface dma_mem_w_ena", false,-1);
        tracep->declBit(c+27,"top u_Memory_Interface dma_mem_r_ena", false,-1);
        tracep->declBus(c+29,"top u_Memory_Interface dma_w_data", false,-1, 7,0);
        tracep->declBus(c+302,"top u_Memory_Interface dma_r_data", false,-1, 7,0);
        tracep->declBit(c+374,"top u_Memory_Interface ROM_ena", false,-1);
        tracep->declBus(c+375,"top u_Memory_Interface ROM_ad", false,-1, 20,0);
        tracep->declBit(c+376,"top u_Memory_Interface ROM_r_ena", false,-1);
        tracep->declBit(c+377,"top u_Memory_Interface ROM_w_ena", false,-1);
        tracep->declBus(c+378,"top u_Memory_Interface ROM_w_data", false,-1, 7,0);
        tracep->declBus(c+379,"top u_Memory_Interface ROM_r_data", false,-1, 7,0);
        tracep->declBit(c+380,"top u_Memory_Interface VRAM_ena", false,-1);
        tracep->declBus(c+381,"top u_Memory_Interface VRAM_ad", false,-1, 15,0);
        tracep->declBit(c+382,"top u_Memory_Interface VRAM_r_ena", false,-1);
        tracep->declBit(c+383,"top u_Memory_Interface VRAM_w_ena", false,-1);
        tracep->declBus(c+384,"top u_Memory_Interface VRAM_w_data", false,-1, 7,0);
        tracep->declBus(c+385,"top u_Memory_Interface VRAM_r_data", false,-1, 7,0);
        tracep->declBit(c+392,"top u_Memory_Interface ERAM_ena", false,-1);
        tracep->declBus(c+393,"top u_Memory_Interface ERAM_ad", false,-1, 14,0);
        tracep->declBit(c+394,"top u_Memory_Interface ERAM_r_ena", false,-1);
        tracep->declBit(c+395,"top u_Memory_Interface ERAM_w_ena", false,-1);
        tracep->declBus(c+396,"top u_Memory_Interface ERAM_w_data", false,-1, 7,0);
        tracep->declBus(c+397,"top u_Memory_Interface ERAM_r_data", false,-1, 7,0);
        tracep->declBit(c+386,"top u_Memory_Interface WRAM_ena", false,-1);
        tracep->declBus(c+387,"top u_Memory_Interface WRAM_ad", false,-1, 15,0);
        tracep->declBit(c+388,"top u_Memory_Interface WRAM_r_ena", false,-1);
        tracep->declBit(c+389,"top u_Memory_Interface WRAM_w_ena", false,-1);
        tracep->declBus(c+390,"top u_Memory_Interface WRAM_w_data", false,-1, 7,0);
        tracep->declBus(c+391,"top u_Memory_Interface WRAM_r_data", false,-1, 7,0);
        tracep->declBit(c+398,"top u_Memory_Interface OAM_ena", false,-1);
        tracep->declBus(c+399,"top u_Memory_Interface OAM_ad", false,-1, 15,0);
        tracep->declBit(c+400,"top u_Memory_Interface OAM_r_ena", false,-1);
        tracep->declBit(c+401,"top u_Memory_Interface OAM_w_ena", false,-1);
        tracep->declBus(c+402,"top u_Memory_Interface OAM_w_data", false,-1, 7,0);
        tracep->declBus(c+403,"top u_Memory_Interface OAM_r_data", false,-1, 7,0);
        tracep->declBit(c+404,"top u_Memory_Interface HRAM_ena", false,-1);
        tracep->declBus(c+405,"top u_Memory_Interface HRAM_ad", false,-1, 15,0);
        tracep->declBit(c+406,"top u_Memory_Interface HRAM_r_ena", false,-1);
        tracep->declBit(c+407,"top u_Memory_Interface HRAM_w_ena", false,-1);
        tracep->declBus(c+408,"top u_Memory_Interface HRAM_w_data", false,-1, 7,0);
        tracep->declBus(c+409,"top u_Memory_Interface HRAM_r_data", false,-1, 7,0);
        tracep->declBit(c+303,"top u_Memory_Interface io_reg_ena", false,-1);
        tracep->declBus(c+304,"top u_Memory_Interface io_reg_ad", false,-1, 15,0);
        tracep->declBit(c+305,"top u_Memory_Interface io_reg_r_ena", false,-1);
        tracep->declBit(c+306,"top u_Memory_Interface io_reg_w_ena", false,-1);
        tracep->declBus(c+307,"top u_Memory_Interface io_reg_w_data", false,-1, 7,0);
        tracep->declBus(c+30,"top u_Memory_Interface io_reg_r_data", false,-1, 7,0);
        tracep->declBus(c+414,"top u_Memory_Interface MBC_version", false,-1, 3,0);
        tracep->declBus(c+415,"top u_Memory_Interface ROM_size", false,-1, 7,0);
        tracep->declBus(c+416,"top u_Memory_Interface RAM_size", false,-1, 7,0);
        tracep->declBus(c+343,"top u_Memory_Interface bank_mask", false,-1, 6,0);
        tracep->declBus(c+344,"top u_Memory_Interface ram_mask", false,-1, 1,0);
        tracep->declBit(c+345,"top u_Memory_Interface dma_main_req", false,-1);
        tracep->declBit(c+346,"top u_Memory_Interface dma_oam_req", false,-1);
        tracep->declBit(c+347,"top u_Memory_Interface ppu_vram_req", false,-1);
        tracep->declBit(c+348,"top u_Memory_Interface ppu_oam_req", false,-1);
        tracep->declBit(c+349,"top u_Memory_Interface cpu_main_req", false,-1);
        tracep->declBit(c+350,"top u_Memory_Interface cpu_hram_req", false,-1);
        tracep->declBit(c+351,"top u_Memory_Interface cpu_vram_req", false,-1);
        tracep->declBit(c+352,"top u_Memory_Interface cpu_oam_req", false,-1);
        tracep->declBus(c+293,"top u_Memory_Interface cpu_state", false,-1, 3,0);
        tracep->declBus(c+353,"top u_Memory_Interface cpu_next", false,-1, 3,0);
        tracep->declBus(c+294,"top u_Memory_Interface ppu_state", false,-1, 3,0);
        tracep->declBus(c+354,"top u_Memory_Interface ppu_next", false,-1, 3,0);
        tracep->declBus(c+295,"top u_Memory_Interface dma_state", false,-1, 3,0);
        tracep->declBus(c+355,"top u_Memory_Interface dma_next", false,-1, 3,0);
        tracep->declBus(c+296,"top u_Memory_Interface MBC1_0000_1FFF", false,-1, 7,0);
        tracep->declBus(c+297,"top u_Memory_Interface MBC1_2000_3FFF", false,-1, 4,0);
        tracep->declBus(c+298,"top u_Memory_Interface MBC1_4000_5FFF", false,-1, 1,0);
        tracep->declBit(c+299,"top u_Memory_Interface MBC1_6000_7FFF", false,-1);
        tracep->declBit(c+356,"top u_Memory_Interface MBC1_0000_w_ena", false,-1);
        tracep->declBit(c+357,"top u_Memory_Interface MBC1_2000_w_ena", false,-1);
        tracep->declBit(c+358,"top u_Memory_Interface MBC1_4000_w_ena", false,-1);
        tracep->declBit(c+359,"top u_Memory_Interface MBC1_6000_w_ena", false,-1);
        tracep->declBus(c+360,"top u_Memory_Interface MBC1_0000_w_data", false,-1, 7,0);
        tracep->declBus(c+361,"top u_Memory_Interface MBC1_2000_w_data", false,-1, 4,0);
        tracep->declBus(c+362,"top u_Memory_Interface MBC1_4000_w_data", false,-1, 1,0);
        tracep->declBit(c+363,"top u_Memory_Interface MBC1_6000_w_data", false,-1);
        tracep->declBit(c+364,"top u_OAM_DMA clk", false,-1);
        tracep->declBit(c+365,"top u_OAM_DMA reset", false,-1);
        tracep->declBit(c+25,"top u_OAM_DMA mem_ena", false,-1);
        tracep->declBit(c+27,"top u_OAM_DMA mem_r_ena", false,-1);
        tracep->declBit(c+28,"top u_OAM_DMA mem_w_ena", false,-1);
        tracep->declBus(c+26,"top u_OAM_DMA mem_ad", false,-1, 15,0);
        tracep->declBus(c+29,"top u_OAM_DMA mem_w_data", false,-1, 7,0);
        tracep->declBus(c+302,"top u_OAM_DMA mem_r_data", false,-1, 7,0);
        tracep->declBus(c+12,"top u_OAM_DMA DMA", false,-1, 7,0);
        tracep->declBit(c+31,"top u_OAM_DMA DMA_start", false,-1);
        tracep->declBus(c+285,"top u_OAM_DMA state", false,-1, 3,0);
        tracep->declBus(c+286,"top u_OAM_DMA clk_counter", false,-1, 7,0);
        tracep->declBus(c+287,"top u_OAM_DMA real_clk_counter", false,-1, 15,0);
        tracep->declBus(c+288,"top u_OAM_DMA tem_reg", false,-1, 7,0);
        tracep->declBus(c+289,"top u_OAM_DMA r_ad_reg", false,-1, 15,0);
        tracep->declBus(c+290,"top u_OAM_DMA w_ad_reg", false,-1, 15,0);
        tracep->declBit(c+291,"top u_OAM_DMA w_end", false,-1);
        tracep->declBit(c+292,"top u_OAM_DMA r_end", false,-1);
    }
}

void Vcpu::traceRegister(VerilatedVcd* tracep) {
    // Body
    {
        tracep->addFullCb(&traceFullTop0, __VlSymsp);
        tracep->addChgCb(&traceChgTop0, __VlSymsp);
        tracep->addCleanupCb(&traceCleanup, __VlSymsp);
    }
}

void Vcpu::traceFullTop0(void* userp, VerilatedVcd* tracep) {
    Vcpu__Syms* __restrict vlSymsp = static_cast<Vcpu__Syms*>(userp);
    Vcpu* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    // Body
    {
        vlTOPp->traceFullSub0(userp, tracep);
    }
}

void Vcpu::traceFullSub0(void* userp, VerilatedVcd* tracep) {
    Vcpu__Syms* __restrict vlSymsp = static_cast<Vcpu__Syms*>(userp);
    Vcpu* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    vluint32_t* const oldp = tracep->oldp(vlSymsp->__Vm_baseCode);
    if (false && oldp) {}  // Prevent unused
    // Body
    {
        tracep->fullCData(oldp+1,((0xe0U | (IData)(vlTOPp->top__DOT__u_io_register__DOT__inst_IF__DOT__IF_reg))),8);
        tracep->fullCData(oldp+2,((0xe0U | (IData)(vlTOPp->top__DOT__u_io_register__DOT__inst_IE__DOT__IE_reg))),8);
        tracep->fullCData(oldp+3,(vlTOPp->top__DOT__u_io_register__DOT__inst_PPU_IO__DOT__LCDC_reg),8);
        tracep->fullCData(oldp+4,(vlTOPp->top__DOT__u_io_register__DOT__inst_STAT__DOT__STAT_reg),8);
        tracep->fullCData(oldp+5,(vlTOPp->top__DOT__u_io_register__DOT__inst_PPU_IO__DOT__SCY_reg),8);
        tracep->fullCData(oldp+6,(vlTOPp->top__DOT__u_io_register__DOT__inst_PPU_IO__DOT__SCX_reg),8);
        tracep->fullCData(oldp+7,(vlTOPp->top__DOT__u_io_register__DOT__inst_PPU_IO__DOT__WX_reg),8);
        tracep->fullCData(oldp+8,(vlTOPp->top__DOT__u_io_register__DOT__inst_PPU_IO__DOT__WY_reg),8);
        tracep->fullCData(oldp+9,(vlTOPp->top__DOT__u_io_register__DOT__inst_PPU_IO__DOT__BGP_reg),8);
        tracep->fullCData(oldp+10,(vlTOPp->top__DOT__u_io_register__DOT__inst_PPU_IO__DOT__OBP0_reg),8);
        tracep->fullCData(oldp+11,(vlTOPp->top__DOT__u_io_register__DOT__inst_PPU_IO__DOT__OBP1_reg),8);
        tracep->fullCData(oldp+12,(vlTOPp->top__DOT__u_io_register__DOT__inst_DMA__DOT__DMA_reg),8);
        tracep->fullCData(oldp+13,(vlTOPp->top__DOT__u_io_register__DOT__inst_LY__DOT__LY_reg),8);
        tracep->fullCData(oldp+14,(vlTOPp->top__DOT__u_io_register__DOT__inst_PPU_IO__DOT__LYC_reg),8);
        tracep->fullBit(oldp+15,(vlTOPp->top__DOT__cpu_mem_ena));
        tracep->fullSData(oldp+16,(vlTOPp->top__DOT__cpu_mem_ad),16);
        tracep->fullBit(oldp+17,(vlTOPp->top__DOT__cpu_mem_r_ena));
        tracep->fullBit(oldp+18,(vlTOPp->top__DOT__cpu_mem_w_ena));
        tracep->fullCData(oldp+19,(vlTOPp->top__DOT__cpu_mem_w_data),8);
        tracep->fullBit(oldp+20,(vlTOPp->top__DOT__ppu_mem_ena));
        tracep->fullSData(oldp+21,(vlTOPp->top__DOT__ppu_mem_ad),16);
        tracep->fullBit(oldp+22,(vlTOPp->top__DOT__ppu_mem_r_ena));
        tracep->fullBit(oldp+23,(vlTOPp->top__DOT__ppu_mem_w_ena));
        tracep->fullCData(oldp+24,(vlTOPp->top__DOT__ppu_mem_w_data),8);
        tracep->fullBit(oldp+25,(vlTOPp->top__DOT__dma_mem_ena));
        tracep->fullSData(oldp+26,(vlTOPp->top__DOT__dma_mem_ad),16);
        tracep->fullBit(oldp+27,(vlTOPp->top__DOT__dma_mem_r_ena));
        tracep->fullBit(oldp+28,(vlTOPp->top__DOT__dma_mem_w_ena));
        tracep->fullCData(oldp+29,(vlTOPp->top__DOT__dma_mem_w_data),8);
        tracep->fullCData(oldp+30,(vlTOPp->top__DOT__io_reg_r_data),8);
        tracep->fullBit(oldp+31,(vlTOPp->top__DOT__u_io_register__DOT__DMA_start));
        tracep->fullCData(oldp+32,(vlTOPp->top__DOT__irq_clear),8);
        tracep->fullBit(oldp+33,(vlTOPp->top__DOT__irq_LCD));
        tracep->fullBit(oldp+34,(vlTOPp->top__DOT__irq_vblank));
        tracep->fullBit(oldp+35,(vlTOPp->top__DOT__PPU_STAT_w_ena));
        tracep->fullCData(oldp+36,(vlTOPp->top__DOT__PPU_STAT_w_data),8);
        tracep->fullBit(oldp+37,(vlTOPp->top__DOT__PPU_LY_w_ena));
        tracep->fullCData(oldp+38,(vlTOPp->top__DOT__PPU_LY_w_data),8);
        tracep->fullBit(oldp+39,(vlTOPp->top__DOT__u_CPU__DOT__halt));
        tracep->fullCData(oldp+40,(vlTOPp->top__DOT__u_CPU__DOT__A),8);
        tracep->fullCData(oldp+41,(vlTOPp->top__DOT__u_CPU__DOT__F),8);
        tracep->fullCData(oldp+42,(vlTOPp->top__DOT__u_CPU__DOT__B),8);
        tracep->fullCData(oldp+43,(vlTOPp->top__DOT__u_CPU__DOT__C),8);
        tracep->fullCData(oldp+44,(vlTOPp->top__DOT__u_CPU__DOT__D),8);
        tracep->fullCData(oldp+45,(vlTOPp->top__DOT__u_CPU__DOT__E),8);
        tracep->fullCData(oldp+46,(vlTOPp->top__DOT__u_CPU__DOT__H),8);
        tracep->fullCData(oldp+47,(vlTOPp->top__DOT__u_CPU__DOT__L),8);
        tracep->fullSData(oldp+48,(vlTOPp->top__DOT__u_CPU__DOT__PC),16);
        tracep->fullSData(oldp+49,(vlTOPp->top__DOT__u_CPU__DOT__SP),16);
        tracep->fullCData(oldp+50,(vlTOPp->top__DOT__u_CPU__DOT__main_state),8);
        tracep->fullBit(oldp+51,(vlTOPp->top__DOT__u_CPU__DOT__IME));
        tracep->fullBit(oldp+52,(vlTOPp->top__DOT__u_CPU__DOT__IME_on));
        tracep->fullBit(oldp+53,(vlTOPp->top__DOT__u_CPU__DOT__IME_off));
        tracep->fullBit(oldp+54,(vlTOPp->top__DOT__u_CPU__DOT__EI_pending));
        tracep->fullBit(oldp+55,(vlTOPp->top__DOT__u_CPU__DOT__EI_pending_on));
        tracep->fullCData(oldp+56,(vlTOPp->top__DOT__u_CPU__DOT__IF_reg),8);
        tracep->fullCData(oldp+57,(vlTOPp->top__DOT__u_CPU__DOT__Operand_r8_ad),8);
        tracep->fullCData(oldp+58,(vlTOPp->top__DOT__u_CPU__DOT__Dest_r8),8);
        tracep->fullBit(oldp+59,(vlTOPp->top__DOT__u_CPU__DOT__Condition));
        tracep->fullCData(oldp+60,(vlTOPp->top__DOT__u_CPU__DOT__Operand_r16_ad),8);
        tracep->fullSData(oldp+61,(vlTOPp->top__DOT__u_CPU__DOT__Dest_r16mem),16);
        tracep->fullSData(oldp+62,(vlTOPp->top__DOT__u_CPU__DOT__Source_r16mem),16);
        tracep->fullCData(oldp+63,(vlTOPp->top__DOT__u_CPU__DOT__register_r16stk_ad),8);
        tracep->fullCData(oldp+64,(vlTOPp->top__DOT__u_CPU__DOT__T_clk_counter),8);
        tracep->fullCData(oldp+65,(vlTOPp->top__DOT__u_CPU__DOT__T_clk_counter_next),8);
        tracep->fullCData(oldp+66,(vlTOPp->top__DOT__u_CPU__DOT__opcode),8);
        tracep->fullBit(oldp+67,(vlTOPp->top__DOT__u_CPU__DOT__opcode_valid));
        tracep->fullBit(oldp+68,(vlTOPp->top__DOT__u_CPU__DOT__prefix_valid));
        tracep->fullCData(oldp+69,(vlTOPp->top__DOT__u_CPU__DOT__my_clk_counter),4);
        tracep->fullBit(oldp+70,((3U == (IData)(vlTOPp->top__DOT__u_CPU__DOT__my_clk_counter))));
        tracep->fullCData(oldp+71,(vlTOPp->top__DOT__u_CPU__DOT__mem_state),4);
        tracep->fullCData(oldp+72,(vlTOPp->top__DOT__u_CPU__DOT__next_main_state),8);
        tracep->fullBit(oldp+73,(vlTOPp->top__DOT__u_CPU__DOT__reg_w_ena));
        tracep->fullCData(oldp+74,(vlTOPp->top__DOT__u_CPU__DOT__reg_ad),8);
        tracep->fullCData(oldp+75,(vlTOPp->top__DOT__u_CPU__DOT__reg_ad_2),8);
        tracep->fullBit(oldp+76,(vlTOPp->top__DOT__u_CPU__DOT__PC_plus_ena));
        tracep->fullSData(oldp+77,(vlTOPp->top__DOT__u_CPU__DOT__mem_ad_reg),16);
        tracep->fullCData(oldp+78,(vlTOPp->top__DOT__u_CPU__DOT__mem_w_data_reg),8);
        tracep->fullBit(oldp+79,(vlTOPp->top__DOT__u_CPU__DOT__mem_w_ena_reg));
        tracep->fullBit(oldp+80,(vlTOPp->top__DOT__u_CPU__DOT__mem_r_ena_reg));
        tracep->fullCData(oldp+81,(vlTOPp->top__DOT__u_CPU__DOT__mem_out_reg),8);
        tracep->fullBit(oldp+82,(vlTOPp->top__DOT__u_CPU__DOT__mem_control_r_ena));
        tracep->fullBit(oldp+83,(vlTOPp->top__DOT__u_CPU__DOT__mem_control_w_ena));
        tracep->fullSData(oldp+84,(vlTOPp->top__DOT__u_CPU__DOT__mem_control_ad),16);
        tracep->fullCData(oldp+85,(vlTOPp->top__DOT__u_CPU__DOT__tem_reg),8);
        tracep->fullBit(oldp+86,(vlTOPp->top__DOT__u_CPU__DOT__tem_reg_w_ena));
        tracep->fullCData(oldp+87,(vlTOPp->top__DOT__u_CPU__DOT__imm8_reg),8);
        tracep->fullBit(oldp+88,(vlTOPp->top__DOT__u_CPU__DOT__imm8_reg_clear));
        tracep->fullSData(oldp+89,(vlTOPp->top__DOT__u_CPU__DOT__imm16_reg),16);
        tracep->fullBit(oldp+90,(vlTOPp->top__DOT__u_CPU__DOT__imm16_reg_clear));
        tracep->fullCData(oldp+91,(vlTOPp->top__DOT__u_CPU__DOT__a_8),8);
        tracep->fullCData(oldp+92,(vlTOPp->top__DOT__u_CPU__DOT__alu_op_8),5);
        tracep->fullBit(oldp+93,(vlTOPp->top__DOT__u_CPU__DOT__cin_8));
        tracep->fullCData(oldp+94,((0xf8U | (IData)(vlTOPp->top__DOT__u_io_register__DOT__inst_TAC__DOT__TAC_reg))),8);
        tracep->fullCData(oldp+95,(vlTOPp->top__DOT__u_io_register__DOT__inst_TMA__DOT__TMA_reg),8);
        tracep->fullBit(oldp+96,(vlTOPp->top__DOT__u_io_register__DOT__irq_timer_wire));
        tracep->fullCData(oldp+97,(vlTOPp->top__DOT__u_io_register__DOT__div_r_data),8);
        tracep->fullCData(oldp+98,(vlTOPp->top__DOT__u_io_register__DOT__tima_r_data),8);
        tracep->fullCData(oldp+99,(vlTOPp->top__DOT__u_io_register__DOT__tma_r_data),8);
        tracep->fullCData(oldp+100,(vlTOPp->top__DOT__u_io_register__DOT__tac_r_data),8);
        tracep->fullCData(oldp+101,(vlTOPp->top__DOT__u_io_register__DOT__dma_r_data),8);
        tracep->fullCData(oldp+102,(vlTOPp->top__DOT__u_io_register__DOT__ppu_io_r_data),8);
        tracep->fullCData(oldp+103,(vlTOPp->top__DOT__u_io_register__DOT__stat_r_data),8);
        tracep->fullCData(oldp+104,(vlTOPp->top__DOT__u_io_register__DOT__ly_r_data),8);
        tracep->fullCData(oldp+105,(vlTOPp->top__DOT__u_io_register__DOT__r_state),4);
        tracep->fullCData(oldp+106,(vlTOPp->top__DOT__u_io_register__DOT__JOY),8);
        tracep->fullBit(oldp+107,(vlTOPp->top__DOT__u_io_register__DOT__irq_joypad));
        tracep->fullCData(oldp+108,(vlTOPp->top__DOT__u_io_register__DOT__inst_IF__DOT__IF_reg),8);
        tracep->fullCData(oldp+109,(vlTOPp->top__DOT__u_io_register__DOT__inst_IE__DOT__IE_reg),8);
        tracep->fullCData(oldp+110,(vlTOPp->top__DOT__u_io_register__DOT__inst_DIV__DOT__my_clk_counter),5);
        tracep->fullSData(oldp+111,(vlTOPp->top__DOT__u_io_register__DOT__inst_DIV__DOT__T_clk_counter),16);
        tracep->fullCData(oldp+112,(vlTOPp->top__DOT__u_io_register__DOT__inst_TIMA__DOT__TIMA),8);
        tracep->fullCData(oldp+113,(vlTOPp->top__DOT__u_io_register__DOT__inst_TIMA__DOT__my_clk_counter),4);
        tracep->fullSData(oldp+114,(vlTOPp->top__DOT__u_io_register__DOT__inst_TIMA__DOT__T_clk_counter),16);
        tracep->fullBit(oldp+115,(vlTOPp->top__DOT__u_io_register__DOT__inst_TIMA__DOT__T_cycle_ena));
        tracep->fullBit(oldp+116,(vlTOPp->top__DOT__u_io_register__DOT__inst_TIMA__DOT__M_cycle_ena));
        tracep->fullSData(oldp+117,(vlTOPp->top__DOT__u_io_register__DOT__inst_TIMA__DOT__M_4_counter),16);
        tracep->fullSData(oldp+118,(vlTOPp->top__DOT__u_io_register__DOT__inst_TIMA__DOT__M_16_counter),16);
        tracep->fullSData(oldp+119,(vlTOPp->top__DOT__u_io_register__DOT__inst_TIMA__DOT__M_64_counter),16);
        tracep->fullSData(oldp+120,(vlTOPp->top__DOT__u_io_register__DOT__inst_TIMA__DOT__M_256_counter),16);
        tracep->fullBit(oldp+121,(vlTOPp->top__DOT__u_io_register__DOT__inst_TIMA__DOT__TIMA_M_4_ena));
        tracep->fullBit(oldp+122,(vlTOPp->top__DOT__u_io_register__DOT__inst_TIMA__DOT__TIMA_M_16_ena));
        tracep->fullBit(oldp+123,(vlTOPp->top__DOT__u_io_register__DOT__inst_TIMA__DOT__TIMA_M_64_ena));
        tracep->fullBit(oldp+124,(vlTOPp->top__DOT__u_io_register__DOT__inst_TIMA__DOT__TIMA_M_256_ena));
        tracep->fullBit(oldp+125,(vlTOPp->top__DOT__u_io_register__DOT__inst_TIMA__DOT__TIMA_ena));
        tracep->fullBit(oldp+126,(vlTOPp->top__DOT__u_io_register__DOT__inst_TIMA__DOT__TIMA_overflow));
        tracep->fullCData(oldp+127,(vlTOPp->top__DOT__u_io_register__DOT__inst_TAC__DOT__TAC_reg),8);
        tracep->fullCData(oldp+128,(vlTOPp->top__DOT__u_PPU__DOT__clk_counter),4);
        tracep->fullBit(oldp+129,((3U == (IData)(vlTOPp->top__DOT__u_PPU__DOT__clk_counter))));
        tracep->fullIData(oldp+130,(vlTOPp->top__DOT__u_PPU__DOT__m_clk_counter),32);
        tracep->fullCData(oldp+131,(vlTOPp->top__DOT__u_PPU__DOT__main_state),5);
        tracep->fullCData(oldp+132,(vlTOPp->top__DOT__u_PPU__DOT__line_counter),8);
        tracep->fullBit(oldp+133,(vlTOPp->top__DOT__u_PPU__DOT__mode0_enter));
        tracep->fullBit(oldp+134,(vlTOPp->top__DOT__u_PPU__DOT__mode1_enter));
        tracep->fullBit(oldp+135,(vlTOPp->top__DOT__u_PPU__DOT__mode2_enter));
        tracep->fullBit(oldp+136,(vlTOPp->top__DOT__u_PPU__DOT__mode3_enter));
        tracep->fullQData(oldp+137,(vlTOPp->top__DOT__u_PPU__DOT__oam_scan),40);
        tracep->fullWData(oldp+139,(vlTOPp->top__DOT__u_PPU__DOT__obj_ad),160);
        tracep->fullWData(oldp+144,(vlTOPp->top__DOT__u_PPU__DOT__obj_y),80);
        tracep->fullWData(oldp+147,(vlTOPp->top__DOT__u_PPU__DOT__obj_x),80);
        tracep->fullWData(oldp+150,(vlTOPp->top__DOT__u_PPU__DOT__obj_tile_index),80);
        tracep->fullWData(oldp+153,(vlTOPp->top__DOT__u_PPU__DOT__obj_flag),80);
        tracep->fullCData(oldp+156,(vlTOPp->top__DOT__u_PPU__DOT__array_index),4);
        tracep->fullCData(oldp+157,(vlTOPp->top__DOT__u_PPU__DOT__valid_obj_counter),4);
        tracep->fullWData(oldp+158,(vlTOPp->top__DOT__u_PPU__DOT__obj_scanline),512);
        tracep->fullWData(oldp+174,(vlTOPp->top__DOT__u_PPU__DOT__obj_priority),256);
        tracep->fullWData(oldp+182,(vlTOPp->top__DOT__u_PPU__DOT__obj_palette),256);
        tracep->fullWData(oldp+190,(vlTOPp->top__DOT__u_PPU__DOT__obj_x_buffer),2048);
        tracep->fullSData(oldp+254,(vlTOPp->top__DOT__u_PPU__DOT__sub_state),16);
        tracep->fullSData(oldp+255,(vlTOPp->top__DOT__u_PPU__DOT__sub_counter_1),16);
        tracep->fullSData(oldp+256,(vlTOPp->top__DOT__u_PPU__DOT__sub_counter_2),16);
        tracep->fullSData(oldp+257,(vlTOPp->top__DOT__u_PPU__DOT__sub_counter_3),16);
        tracep->fullCData(oldp+258,(vlTOPp->top__DOT__u_PPU__DOT__mode3_state),4);
        tracep->fullCData(oldp+259,(vlTOPp->top__DOT__u_PPU__DOT__mode3_counter_1),8);
        tracep->fullCData(oldp+260,(vlTOPp->top__DOT__u_PPU__DOT__map_x),8);
        tracep->fullCData(oldp+261,(vlTOPp->top__DOT__u_PPU__DOT__map_y),8);
        tracep->fullCData(oldp+262,(vlTOPp->top__DOT__u_PPU__DOT__win_x),8);
        tracep->fullCData(oldp+263,(vlTOPp->top__DOT__u_PPU__DOT__win_y),8);
        tracep->fullWData(oldp+264,(vlTOPp->top__DOT__u_PPU__DOT__tile_buffer),512);
        tracep->fullCData(oldp+280,(vlTOPp->top__DOT__u_PPU__DOT__tile_buffer_index),8);
        tracep->fullIData(oldp+281,(vlTOPp->top__DOT__u_PPU__DOT__i),32);
        tracep->fullCData(oldp+282,(vlTOPp->top__DOT__u_PPU__DOT__obj_row),8);
        tracep->fullBit(oldp+283,(((((IData)(vlTOPp->top__DOT__u_io_register__DOT__inst_PPU_IO__DOT__WX_reg) 
                                     <= ((IData)(7U) 
                                         + (IData)(vlTOPp->top__DOT__u_PPU__DOT__sub_counter_2))) 
                                    & ((IData)(vlTOPp->top__DOT__u_io_register__DOT__inst_PPU_IO__DOT__WY_reg) 
                                       <= (IData)(vlTOPp->top__DOT__u_PPU__DOT__line_counter))) 
                                   & ((IData)(vlTOPp->top__DOT__u_io_register__DOT__inst_PPU_IO__DOT__LCDC_reg) 
                                      >> 5U))));
        tracep->fullCData(oldp+284,((7U & (((((IData)(vlTOPp->top__DOT__u_io_register__DOT__inst_PPU_IO__DOT__WX_reg) 
                                              <= ((IData)(7U) 
                                                  + (IData)(vlTOPp->top__DOT__u_PPU__DOT__sub_counter_2))) 
                                             & ((IData)(vlTOPp->top__DOT__u_io_register__DOT__inst_PPU_IO__DOT__WY_reg) 
                                                <= (IData)(vlTOPp->top__DOT__u_PPU__DOT__line_counter))) 
                                            & ((IData)(vlTOPp->top__DOT__u_io_register__DOT__inst_PPU_IO__DOT__LCDC_reg) 
                                               >> 5U))
                                            ? (IData)(vlTOPp->top__DOT__u_PPU__DOT__win_x)
                                            : (IData)(vlTOPp->top__DOT__u_PPU__DOT__map_x)))),3);
        tracep->fullCData(oldp+285,(vlTOPp->top__DOT__u_OAM_DMA__DOT__state),4);
        tracep->fullCData(oldp+286,(vlTOPp->top__DOT__u_OAM_DMA__DOT__clk_counter),8);
        tracep->fullSData(oldp+287,(vlTOPp->top__DOT__u_OAM_DMA__DOT__real_clk_counter),16);
        tracep->fullCData(oldp+288,(vlTOPp->top__DOT__u_OAM_DMA__DOT__tem_reg),8);
        tracep->fullSData(oldp+289,(vlTOPp->top__DOT__u_OAM_DMA__DOT__r_ad_reg),16);
        tracep->fullSData(oldp+290,(vlTOPp->top__DOT__u_OAM_DMA__DOT__w_ad_reg),16);
        tracep->fullBit(oldp+291,(vlTOPp->top__DOT__u_OAM_DMA__DOT__w_end));
        tracep->fullBit(oldp+292,(vlTOPp->top__DOT__u_OAM_DMA__DOT__r_end));
        tracep->fullCData(oldp+293,(vlTOPp->top__DOT__u_Memory_Interface__DOT__cpu_state),4);
        tracep->fullCData(oldp+294,(vlTOPp->top__DOT__u_Memory_Interface__DOT__ppu_state),4);
        tracep->fullCData(oldp+295,(vlTOPp->top__DOT__u_Memory_Interface__DOT__dma_state),4);
        tracep->fullCData(oldp+296,(vlTOPp->top__DOT__u_Memory_Interface__DOT__MBC1_0000_1FFF),8);
        tracep->fullCData(oldp+297,(vlTOPp->top__DOT__u_Memory_Interface__DOT__MBC1_2000_3FFF),5);
        tracep->fullCData(oldp+298,(vlTOPp->top__DOT__u_Memory_Interface__DOT__MBC1_4000_5FFF),2);
        tracep->fullBit(oldp+299,(vlTOPp->top__DOT__u_Memory_Interface__DOT__MBC1_6000_7FFF));
        tracep->fullCData(oldp+300,(vlTOPp->top__DOT__cpu_mem_r_data),8);
        tracep->fullCData(oldp+301,(vlTOPp->top__DOT__ppu_mem_r_data),8);
        tracep->fullCData(oldp+302,(vlTOPp->top__DOT__dma_mem_r_data),8);
        tracep->fullBit(oldp+303,(vlTOPp->top__DOT__io_reg_ena));
        tracep->fullSData(oldp+304,(vlTOPp->top__DOT__io_reg_ad),16);
        tracep->fullBit(oldp+305,(vlTOPp->top__DOT__io_reg_r_ena));
        tracep->fullBit(oldp+306,(vlTOPp->top__DOT__io_reg_w_ena));
        tracep->fullCData(oldp+307,(vlTOPp->top__DOT__io_reg_w_data),8);
        tracep->fullCData(oldp+308,(vlTOPp->top__DOT__u_CPU__DOT__Operand_r8),8);
        tracep->fullCData(oldp+309,(vlTOPp->top__DOT__u_CPU__DOT__Source_r8),8);
        tracep->fullSData(oldp+310,(vlTOPp->top__DOT__u_CPU__DOT__Operand_r16),16);
        tracep->fullSData(oldp+311,(vlTOPp->top__DOT__u_CPU__DOT__register_r16stk),16);
        tracep->fullSData(oldp+312,(vlTOPp->top__DOT__u_CPU__DOT__reg_w_data),16);
        tracep->fullSData(oldp+313,(vlTOPp->top__DOT__u_CPU__DOT__reg_w_data_2),16);
        tracep->fullCData(oldp+314,(vlTOPp->top__DOT__u_CPU__DOT__mem_control_w_data),8);
        tracep->fullCData(oldp+315,(vlTOPp->top__DOT__u_CPU__DOT__tem_reg_w_data),8);
        tracep->fullCData(oldp+316,(vlTOPp->top__DOT__u_CPU__DOT__b_8),8);
        tracep->fullCData(oldp+317,(vlTOPp->top__DOT__u_CPU__DOT__flag_8),4);
        tracep->fullCData(oldp+318,(vlTOPp->top__DOT__u_CPU__DOT__alu_result_8),8);
        tracep->fullSData(oldp+319,(vlTOPp->top__DOT__u_CPU__DOT__ins00__DOT__tem9),9);
        tracep->fullCData(oldp+320,(vlTOPp->top__DOT__u_CPU__DOT__ins00__DOT__tem5),5);
        tracep->fullBit(oldp+321,(vlTOPp->top__DOT__u_io_register__DOT__IF_w_ena));
        tracep->fullBit(oldp+322,(vlTOPp->top__DOT__u_io_register__DOT__IE_w_ena));
        tracep->fullBit(oldp+323,(vlTOPp->top__DOT__u_io_register__DOT__div_w_ena));
        tracep->fullBit(oldp+324,(vlTOPp->top__DOT__u_io_register__DOT__div_r_ena));
        tracep->fullBit(oldp+325,(vlTOPp->top__DOT__u_io_register__DOT__tima_w_ena));
        tracep->fullBit(oldp+326,(vlTOPp->top__DOT__u_io_register__DOT__tima_r_ena));
        tracep->fullBit(oldp+327,(vlTOPp->top__DOT__u_io_register__DOT__tma_r_ena));
        tracep->fullBit(oldp+328,(vlTOPp->top__DOT__u_io_register__DOT__tma_w_ena));
        tracep->fullBit(oldp+329,(vlTOPp->top__DOT__u_io_register__DOT__tac_r_ena));
        tracep->fullBit(oldp+330,(vlTOPp->top__DOT__u_io_register__DOT__tac_w_ena));
        tracep->fullBit(oldp+331,(vlTOPp->top__DOT__u_io_register__DOT__dma_r_ena));
        tracep->fullBit(oldp+332,(vlTOPp->top__DOT__u_io_register__DOT__dma_w_ena));
        tracep->fullBit(oldp+333,(vlTOPp->top__DOT__u_io_register__DOT__ppu_io_r_ena));
        tracep->fullBit(oldp+334,(vlTOPp->top__DOT__u_io_register__DOT__ppu_io_w_ena));
        tracep->fullBit(oldp+335,(vlTOPp->top__DOT__u_io_register__DOT__stat_r_ena));
        tracep->fullBit(oldp+336,(vlTOPp->top__DOT__u_io_register__DOT__stat_w_ena));
        tracep->fullBit(oldp+337,(vlTOPp->top__DOT__u_io_register__DOT__ly_r_ena));
        tracep->fullBit(oldp+338,(vlTOPp->top__DOT__u_io_register__DOT__ly_w_ena));
        tracep->fullBit(oldp+339,(vlTOPp->top__DOT__u_io_register__DOT__joy_r_ena));
        tracep->fullBit(oldp+340,(vlTOPp->top__DOT__u_io_register__DOT__joy_w_ena));
        tracep->fullCData(oldp+341,(vlTOPp->top__DOT__u_io_register__DOT__next),4);
        tracep->fullCData(oldp+342,(vlTOPp->top__DOT__u_PPU__DOT__shifted_data),8);
        tracep->fullCData(oldp+343,(vlTOPp->top__DOT__u_Memory_Interface__DOT__bank_mask),7);
        tracep->fullCData(oldp+344,(vlTOPp->top__DOT__u_Memory_Interface__DOT__ram_mask),2);
        tracep->fullBit(oldp+345,(vlTOPp->top__DOT__u_Memory_Interface__DOT__dma_main_req));
        tracep->fullBit(oldp+346,(vlTOPp->top__DOT__u_Memory_Interface__DOT__dma_oam_req));
        tracep->fullBit(oldp+347,(vlTOPp->top__DOT__u_Memory_Interface__DOT__ppu_vram_req));
        tracep->fullBit(oldp+348,(vlTOPp->top__DOT__u_Memory_Interface__DOT__ppu_oam_req));
        tracep->fullBit(oldp+349,(vlTOPp->top__DOT__u_Memory_Interface__DOT__cpu_main_req));
        tracep->fullBit(oldp+350,(vlTOPp->top__DOT__u_Memory_Interface__DOT__cpu_hram_req));
        tracep->fullBit(oldp+351,(vlTOPp->top__DOT__u_Memory_Interface__DOT__cpu_vram_req));
        tracep->fullBit(oldp+352,(vlTOPp->top__DOT__u_Memory_Interface__DOT__cpu_oam_req));
        tracep->fullCData(oldp+353,(vlTOPp->top__DOT__u_Memory_Interface__DOT__cpu_next),4);
        tracep->fullCData(oldp+354,(vlTOPp->top__DOT__u_Memory_Interface__DOT__ppu_next),4);
        tracep->fullCData(oldp+355,(vlTOPp->top__DOT__u_Memory_Interface__DOT__dma_next),4);
        tracep->fullBit(oldp+356,(vlTOPp->top__DOT__u_Memory_Interface__DOT__MBC1_0000_w_ena));
        tracep->fullBit(oldp+357,(vlTOPp->top__DOT__u_Memory_Interface__DOT__MBC1_2000_w_ena));
        tracep->fullBit(oldp+358,(vlTOPp->top__DOT__u_Memory_Interface__DOT__MBC1_4000_w_ena));
        tracep->fullBit(oldp+359,(vlTOPp->top__DOT__u_Memory_Interface__DOT__MBC1_6000_w_ena));
        tracep->fullCData(oldp+360,(vlTOPp->top__DOT__u_Memory_Interface__DOT__MBC1_0000_w_data),8);
        tracep->fullCData(oldp+361,(vlTOPp->top__DOT__u_Memory_Interface__DOT__MBC1_2000_w_data),5);
        tracep->fullCData(oldp+362,(vlTOPp->top__DOT__u_Memory_Interface__DOT__MBC1_4000_w_data),2);
        tracep->fullBit(oldp+363,(vlTOPp->top__DOT__u_Memory_Interface__DOT__MBC1_6000_w_data));
        tracep->fullBit(oldp+364,(vlTOPp->clk));
        tracep->fullBit(oldp+365,(vlTOPp->reset));
        tracep->fullBit(oldp+366,(vlTOPp->joypad_start));
        tracep->fullBit(oldp+367,(vlTOPp->joypad_select));
        tracep->fullBit(oldp+368,(vlTOPp->joypad_A));
        tracep->fullBit(oldp+369,(vlTOPp->joypad_B));
        tracep->fullBit(oldp+370,(vlTOPp->joypad_down));
        tracep->fullBit(oldp+371,(vlTOPp->joypad_up));
        tracep->fullBit(oldp+372,(vlTOPp->joypad_left));
        tracep->fullBit(oldp+373,(vlTOPp->joypad_right));
        tracep->fullBit(oldp+374,(vlTOPp->ROM_ena));
        tracep->fullIData(oldp+375,(vlTOPp->ROM_ad),21);
        tracep->fullBit(oldp+376,(vlTOPp->ROM_r_ena));
        tracep->fullBit(oldp+377,(vlTOPp->ROM_w_ena));
        tracep->fullCData(oldp+378,(vlTOPp->ROM_w_data),8);
        tracep->fullCData(oldp+379,(vlTOPp->ROM_r_data),8);
        tracep->fullBit(oldp+380,(vlTOPp->VRAM_ena));
        tracep->fullSData(oldp+381,(vlTOPp->VRAM_ad),16);
        tracep->fullBit(oldp+382,(vlTOPp->VRAM_r_ena));
        tracep->fullBit(oldp+383,(vlTOPp->VRAM_w_ena));
        tracep->fullCData(oldp+384,(vlTOPp->VRAM_w_data),8);
        tracep->fullCData(oldp+385,(vlTOPp->VRAM_r_data),8);
        tracep->fullBit(oldp+386,(vlTOPp->WRAM_ena));
        tracep->fullSData(oldp+387,(vlTOPp->WRAM_ad),16);
        tracep->fullBit(oldp+388,(vlTOPp->WRAM_r_ena));
        tracep->fullBit(oldp+389,(vlTOPp->WRAM_w_ena));
        tracep->fullCData(oldp+390,(vlTOPp->WRAM_w_data),8);
        tracep->fullCData(oldp+391,(vlTOPp->WRAM_r_data),8);
        tracep->fullBit(oldp+392,(vlTOPp->ERAM_ena));
        tracep->fullSData(oldp+393,(vlTOPp->ERAM_ad),15);
        tracep->fullBit(oldp+394,(vlTOPp->ERAM_r_ena));
        tracep->fullBit(oldp+395,(vlTOPp->ERAM_w_ena));
        tracep->fullCData(oldp+396,(vlTOPp->ERAM_w_data),8);
        tracep->fullCData(oldp+397,(vlTOPp->ERAM_r_data),8);
        tracep->fullBit(oldp+398,(vlTOPp->OAM_ena));
        tracep->fullSData(oldp+399,(vlTOPp->OAM_ad),16);
        tracep->fullBit(oldp+400,(vlTOPp->OAM_r_ena));
        tracep->fullBit(oldp+401,(vlTOPp->OAM_w_ena));
        tracep->fullCData(oldp+402,(vlTOPp->OAM_w_data),8);
        tracep->fullCData(oldp+403,(vlTOPp->OAM_r_data),8);
        tracep->fullBit(oldp+404,(vlTOPp->HRAM_ena));
        tracep->fullSData(oldp+405,(vlTOPp->HRAM_ad),16);
        tracep->fullBit(oldp+406,(vlTOPp->HRAM_r_ena));
        tracep->fullBit(oldp+407,(vlTOPp->HRAM_w_ena));
        tracep->fullCData(oldp+408,(vlTOPp->HRAM_w_data),8);
        tracep->fullCData(oldp+409,(vlTOPp->HRAM_r_data),8);
        tracep->fullCData(oldp+410,(vlTOPp->pixel_data),2);
        tracep->fullBit(oldp+411,(vlTOPp->pixel_valid));
        tracep->fullBit(oldp+412,(vlTOPp->hsync));
        tracep->fullBit(oldp+413,(vlTOPp->vsync));
        tracep->fullCData(oldp+414,(vlTOPp->MBC_version),4);
        tracep->fullCData(oldp+415,(vlTOPp->ROM_size),8);
        tracep->fullCData(oldp+416,(vlTOPp->RAM_size),8);
        tracep->fullBit(oldp+417,(vlTOPp->top__DOT__irq_joypad));
        tracep->fullBit(oldp+418,(0U));
        tracep->fullCData(oldp+419,(vlTOPp->top__DOT__u_CPU__DOT__mem_r_data_valid),8);
        tracep->fullBit(oldp+420,(vlTOPp->top__DOT__u_CPU__DOT__M_cycle_ena));
        tracep->fullIData(oldp+421,(0U),32);
        tracep->fullIData(oldp+422,(1U),32);
        tracep->fullIData(oldp+423,(2U),32);
        tracep->fullIData(oldp+424,(3U),32);
        tracep->fullIData(oldp+425,(4U),32);
        tracep->fullIData(oldp+426,(5U),32);
        tracep->fullIData(oldp+427,(6U),32);
        tracep->fullIData(oldp+428,(7U),32);
        tracep->fullIData(oldp+429,(8U),32);
        tracep->fullIData(oldp+430,(9U),32);
        tracep->fullIData(oldp+431,(0xaU),32);
        tracep->fullIData(oldp+432,(0xbU),32);
        tracep->fullIData(oldp+433,(0xcU),32);
        tracep->fullIData(oldp+434,(0xdU),32);
        tracep->fullIData(oldp+435,(0xeU),32);
        tracep->fullIData(oldp+436,(0xfU),32);
        tracep->fullIData(oldp+437,(0x10U),32);
        tracep->fullIData(oldp+438,(0x11U),32);
        tracep->fullIData(oldp+439,(0x12U),32);
        tracep->fullIData(oldp+440,(0x13U),32);
        tracep->fullIData(oldp+441,(0x14U),32);
        tracep->fullIData(oldp+442,(0x15U),32);
        tracep->fullIData(oldp+443,(0x16U),32);
        tracep->fullIData(oldp+444,(0x17U),32);
        tracep->fullIData(oldp+445,(0x18U),32);
        tracep->fullCData(oldp+446,(vlTOPp->top__DOT__u_io_register__DOT__DIV),8);
        tracep->fullCData(oldp+447,(vlTOPp->top__DOT__u_io_register__DOT__TIMA),8);
    }
}
